### ISSUE TITLE
Q: Livewire: Directive already registered: [sortable]

### ISSUE THREAD

**Issue by nea** [invaders-xx/filament-kanban-board#1]
Ahoy there

Thanks for this plugin.

I tried installing and following your example, but when I do I get the following error:
```
Uncaught Livewire: Directive already registered: [sortable]

  | register | @ | DirectiveManager.js:7
  | registerDirective | @ | Store.js:113
  | value | @ | index.js:42
  | (anonymous) | @ | index.js:9
  | (anonymous) | @ | index.js:72
```

I don't know if it is related to any other plugin I have installed or something as I do not seem to find a better way to trace this.

Maybe you have an idea.

Thanks a lot

**Comment by invaders-xx** [comment]
Hi, I know this issue. It does not affect the use of the plugin and behaviour of the application. I will fix this soon.

**Comment by invaders-xx** [comment]
@nea, fixed with new release
